FROM resin/nuc-debian:jessie

# Install the dependencies
RUN apt-get update && apt-get install vim btrfs-tools mtools dosfstools python3 python3-requests python3-sh python3-parted python3-binaryornot jq -y && rm -rf /var/lib/apt/lists/*

# Add the current directoy in the container
COPY . /app

CMD python3 /app/resinhup.py --config /app/conf/resinhup.conf --debug
