FROM resin/rpi-raspbian:jessie

# Install the dependencies
RUN apt-get update && apt-get install vim btrfs-tools mtools dosfstools python3 python3-requests python3-sh jq -y && rm -rf /var/lib/apt/lists/*

# Add the current directoy in the container
ADD . /app

CMD python3 /app/resinhup.py --config /app/conf/resinhup.conf --debug
