name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches:
      - "main"
      - "master"
  push:
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@master # flowzonify 0.4.0
    secrets: inherit
    with:
      balena_slugs: |
        balena_os/balenahup
      custom_publish_matrix: balena_os/balenahup
      custom_finalize_matrix: balena_os/balenahup
